FROM golang as build
WORKDIR /artifact
WORKDIR /source
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN go build -o /artifact/daemon ./service/turn


FROM ubuntu 
WORKDIR /
COPY --from=build /artifact/daemon .
ENTRYPOINT [ "/daemon" ]